# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home"
  weight = 10

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 20
  
[[main]]
  name = "Published Articles"
  parent = "Publications"
  pre = "<i class=\"fas fa-pen-nib\" style=\"color: #fff;\"></i> "
  url = "published_articles"
  weight = 20
  
[[main]]
  name = "Working Papers"
  parent = "Publications"
  pre = "<i class=\"fas fa-pencil-alt\" style=\"color: #fff;\"></i> "
  url = "working_papers"
  weight = 30
  
[[main]]
  name = "Research Statement"
  parent = "Publications"
  pre = "<i class=\"fas fa-search\" style=\"color: #fff;\"></i> "
  url = "research_statement"
  weight = 40


[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 30
  
[[main]]
  name = "Teaching Experience"
  parent = "Teaching"
  pre = "<i class=\"fas fa-chalkboard\" style=\"color: #fff;\"></i> "
  url = "teaching"
  weight = 20
  
[[main]]
  name = "Teaching Philosophy"
  parent = "Teaching"
  pre = "<i class=\"fas fa-archive\" style=\"color: #fff;\"></i> "
  url = "teaching_statement"
  weight = 30

[[main]]
  name = "Job Market Paper"
  url = "#jmp"
  weight = 40
  
[[main]]
  name = "CV"
  url = "files/new_cv.pdf"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60
  
  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
