---
title: "Growth, cycles, and residential investment"
author: "Marcio Santetti"
date: '2021-09-01'
slug: ehr-environmental-exposure-pfas
categories:
  - Research
  - Job Market Paper
tags:
  - JMP
doi: ''
publishDate: '2021-09-01'
publication_types:
  - '1'
publication: ''
summary: 'Cyclical growth, investment, and income distribution'
featured: yes
links:
- icon: file-pdf
  icon_pack: fas
  name: Download PDF
  url: https://marcio.rbind.io/jmp/Santetti_GCRI.pdf
---

## Abstract

The empirical literature on neo-Goodwinian models of growth and distribu- tion still lacks an explicit treatment of capital accumulation. Further, and across different theoretical approaches, residential investment is seen as a crit- ical driver of the business cycle. This paper addresses these two issues. First, through four- and five-dimensional Structural Vector Autoregressive (SVAR) models, cyclical trajectories derived from impulse-response functions confirm profit-led demand and profit-squeeze distribution regimes, in accordance with the cyclical stylized facts in the vein of Goodwin (1967). Second, aggregate in- vestment is then split into its residential and nonresidential categories. Results confirm that residential investment leads the cycle, whereas nonresidential in- vestment lags it. Finally, this study argues that residential investment is, in reality, undertaken by corporations—and not households—, and can therefore not be seen as autonomous to the business cycle, demographics, and financial variables.



<br>

<embed src="/jmp/Santetti_GCRI.pdf" width="800px" height="1000px" align="center" />
